name: flutter_template
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.11.5 <4.0.0"
  flutter: ">=3.41.7"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  dartx: ^1.1.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_platform_widgets: ^7.0.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.1.1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.1
  freezed_annotation: ^2.2.0
  get_it: ^8.0.2
  intl: ^0.20.2
  go_router: ^14.3.0
  injectable: ^2.1.0
  json_annotation: ^4.9.0
  retrofit: ^4.0.3
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_portal: ^1.1.4
  flutter_screenutil: ^5.9.3
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.1.2
  retrofit_generator: ^9.1.4
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  intl_utils: ^2.8.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/imgs/
    - assets/svgs/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
